<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Resources\Random.ico</ApplicationIcon>
    <Authors>valen030</Authors>
    <Company>valen030</Company>
    <Product>LKGBotConfiguration</Product>
    <Description>A simple win app for configuring the music bot.</Description>
    <Copyright>Copyright (c) 2026 valen030</Copyright>
    <PackageIcon>Random128.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/valen030/Longkang-Bot</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="10.0.1" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="WorkerService\" />
  </ItemGroup>

	<ItemGroup>
		<Content Include="WorkerService\**\*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <Content Include="Resources\Random.ico" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="..\LKGServiceBot\Random128.png">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	  <None Include="..\README.md">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>

</Project>